:Author: Will Page
:Email: compenguy@gmail.com
:Date: 18/05/2021
:Revision: 0.1
:License: CC0 (Public Domain)

= Project: carduino

A remote controller for a BLE-connected RC car, built on the Arduino Nano RP2040 Connect.

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Crimp a 2-pin JST female connector, and solder to the 5V and Gnd pins on the Arduino Nano RP2040 Connect. Attach the battery to the power connector.

If not using the USB port for the gamepad, a USB charger or battery bank may be used instead as a no-soldering option.

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 carduino                 => Arduino sketch folder
  ├── carduino.ino        => main Arduino file
  └── ReadMe.adoc         => this file
....

=== License
This project is released to the public domain under a CC0 License.

=== Contributing
To contribute to this project please go to the https://github.com/compenguy/carduino[project page on github].

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name                   | Part number | Quantity
| A1 | Arduino Nano RP2040 Connect | ABX00052    | 1
| B1 | 2S LiPo Battery             |             | 1
| J1 | 2-pin JST connector         |             | 1
| U1 | MicroUSB OTG Adapter        |             | (optional)
| G1 | USB Gamepad                 |             | (optional)
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
